package com.manji.msgservice.model;

import com.manji.msgservice.common.utils.mybatis.model.ModelExample;
import java.util.ArrayList;
import java.util.List;

public class MsgBizTypeExample extends ModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public MsgBizTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public Criteria getCriteria() {
        if (oredCriteria.size() == 0) {createCriteria();}
        return oredCriteria.get(0);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    public void addCriteria(List<Criterion> criteria) {
        getCriteria().getCriteria().addAll(criteria);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_biz_type
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        private boolean ignoreNull;

        private boolean isIgnoreNull() {
            return ignoreNull;
        }

        public Criteria ignoreNull() {
            this.ignoreNull = true;
            return (Criteria) this;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                if (!isIgnoreNull()) {
                    throw new RuntimeException("Value for condition cannot be null");
                }} else {
                    criteria.add(new Criterion(condition));}
                }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                if (!isIgnoreNull()) {
                    throw new RuntimeException("Value for " + property + " cannot be null");
                }} else {
                    criteria.add(new Criterion(condition, value));}
                }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                if (!isIgnoreNull()) {
                    throw new RuntimeException("Between values for " + property + " cannot be null");
                }} else {
                    criteria.add(new Criterion(condition, value1, value2));}
                }

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andTypeTypeIdIsNull() {
            addCriterion("type_type_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdIsNotNull() {
            addCriterion("type_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdEqualTo(Long value) {
            addCriterion("type_type_id =", value, "typeTypeId");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdNotEqualTo(Long value) {
            addCriterion("type_type_id <>", value, "typeTypeId");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdGreaterThan(Long value) {
            addCriterion("type_type_id >", value, "typeTypeId");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("type_type_id >=", value, "typeTypeId");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdLessThan(Long value) {
            addCriterion("type_type_id <", value, "typeTypeId");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("type_type_id <=", value, "typeTypeId");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdIn(List<Long> values) {
            addCriterion("type_type_id in", values, "typeTypeId");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdNotIn(List<Long> values) {
            addCriterion("type_type_id not in", values, "typeTypeId");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdBetween(Long value1, Long value2) {
            addCriterion("type_type_id between", value1, value2, "typeTypeId");
            return (Criteria) this;
        }

        public Criteria andTypeTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("type_type_id not between", value1, value2, "typeTypeId");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("type_name is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("type_name is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("type_name =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("type_name <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("type_name >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("type_name >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("type_name <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("type_name <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("type_name like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("type_name not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("type_name in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("type_name not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("type_name between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("type_name not between", value1, value2, "typeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_biz_type
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}