package com.manji.msgservice.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class MsgInnerRec {

	/**
	 * 发送站内信记录ID
	 * @mbggenerated
	 */
	private Long innerRecId;
	/**
	 * 模板id
	 * @mbggenerated
	 */
	private Long templateId;
	/**
	 * 送出去的时间类型：timely:及时。。。temptime:模版定义的时间段。。。customize：自定义时间段
	 * @mbggenerated
	 */
	private String sendTimeType;
	/**
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * 标题
	 * @mbggenerated
	 */
	private String title;
	/**
	 * 发送内容
	 * @mbggenerated
	 */
	private String content;
	/**
	 * 执行状态：already:已经执行，wait:还未执行
	 * @mbggenerated
	 */
	private String sendStatus;
	/**
	 * @mbggenerated
	 */
	private String redirectType;
	/**
	 * @mbggenerated
	 */
	private String redirectValue;
	/**
	 * @mbggenerated
	 */
	private Integer category;
	/**
	 * @mbggenerated
	 */
	private String businessNumber;
	/**
	 * @mbggenerated
	 */
	private String businessUrl;
	/**
	 * @mbggenerated
	 */
	private String picUrl;
	/**
	 * 时间开始
	 * @mbggenerated
	 */
	private Date liveTime;
	/**
	 * 时间结束
	 * @mbggenerated
	 */
	private Date deadTime;
	/**
	 * 发送时间
	 * @mbggenerated
	 */
	private Date sendTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.inner_rec_id
	 * @return  the value of msg_inner_rec.inner_rec_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "发送站内信记录ID")
	public Long getInnerRecId() {
		return innerRecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.inner_rec_id
	 * @param innerRecId  the value for msg_inner_rec.inner_rec_id
	 * @mbggenerated
	 */
	public void setInnerRecId(Long innerRecId) {
		this.innerRecId = innerRecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.template_id
	 * @return  the value of msg_inner_rec.template_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "模板id")
	public Long getTemplateId() {
		return templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.template_id
	 * @param templateId  the value for msg_inner_rec.template_id
	 * @mbggenerated
	 */
	public void setTemplateId(Long templateId) {
		this.templateId = templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.send_time_type
	 * @return  the value of msg_inner_rec.send_time_type
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "送出去的时间类型：timely:及时。。。temptime:模版定义的时间段。。。customize：自定义时间段")
	public String getSendTimeType() {
		return sendTimeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.send_time_type
	 * @param sendTimeType  the value for msg_inner_rec.send_time_type
	 * @mbggenerated
	 */
	public void setSendTimeType(String sendTimeType) {
		this.sendTimeType = sendTimeType == null ? null : sendTimeType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.type
	 * @return  the value of msg_inner_rec.type
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.type
	 * @param type  the value for msg_inner_rec.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.title
	 * @return  the value of msg_inner_rec.title
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "标题")
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.title
	 * @param title  the value for msg_inner_rec.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.content
	 * @return  the value of msg_inner_rec.content
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "发送内容")
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.content
	 * @param content  the value for msg_inner_rec.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.send_status
	 * @return  the value of msg_inner_rec.send_status
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "执行状态：already:已经执行，wait:还未执行")
	public String getSendStatus() {
		return sendStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.send_status
	 * @param sendStatus  the value for msg_inner_rec.send_status
	 * @mbggenerated
	 */
	public void setSendStatus(String sendStatus) {
		this.sendStatus = sendStatus == null ? null : sendStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.redirect_type
	 * @return  the value of msg_inner_rec.redirect_type
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	public String getRedirectType() {
		return redirectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.redirect_type
	 * @param redirectType  the value for msg_inner_rec.redirect_type
	 * @mbggenerated
	 */
	public void setRedirectType(String redirectType) {
		this.redirectType = redirectType == null ? null : redirectType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.redirect_value
	 * @return  the value of msg_inner_rec.redirect_value
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	public String getRedirectValue() {
		return redirectValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.redirect_value
	 * @param redirectValue  the value for msg_inner_rec.redirect_value
	 * @mbggenerated
	 */
	public void setRedirectValue(String redirectValue) {
		this.redirectValue = redirectValue == null ? null : redirectValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.category
	 * @return  the value of msg_inner_rec.category
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	public Integer getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.category
	 * @param category  the value for msg_inner_rec.category
	 * @mbggenerated
	 */
	public void setCategory(Integer category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.business_number
	 * @return  the value of msg_inner_rec.business_number
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	public String getBusinessNumber() {
		return businessNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.business_number
	 * @param businessNumber  the value for msg_inner_rec.business_number
	 * @mbggenerated
	 */
	public void setBusinessNumber(String businessNumber) {
		this.businessNumber = businessNumber == null ? null : businessNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.business_url
	 * @return  the value of msg_inner_rec.business_url
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	public String getBusinessUrl() {
		return businessUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.business_url
	 * @param businessUrl  the value for msg_inner_rec.business_url
	 * @mbggenerated
	 */
	public void setBusinessUrl(String businessUrl) {
		this.businessUrl = businessUrl == null ? null : businessUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.pic_url
	 * @return  the value of msg_inner_rec.pic_url
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.pic_url
	 * @param picUrl  the value for msg_inner_rec.pic_url
	 * @mbggenerated
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl == null ? null : picUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.live_time
	 * @return  the value of msg_inner_rec.live_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "时间开始")
	public Date getLiveTime() {
		return liveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.live_time
	 * @param liveTime  the value for msg_inner_rec.live_time
	 * @mbggenerated
	 */
	public void setLiveTime(Date liveTime) {
		this.liveTime = liveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.dead_time
	 * @return  the value of msg_inner_rec.dead_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "时间结束")
	public Date getDeadTime() {
		return deadTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.dead_time
	 * @param deadTime  the value for msg_inner_rec.dead_time
	 * @mbggenerated
	 */
	public void setDeadTime(Date deadTime) {
		this.deadTime = deadTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_inner_rec.send_time
	 * @return  the value of msg_inner_rec.send_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "发送时间")
	public Date getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_inner_rec.send_time
	 * @param sendTime  the value for msg_inner_rec.send_time
	 * @mbggenerated
	 */
	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}
}