package com.manji.msgservice.model;

import com.manji.msgservice.common.utils.mybatis.model.ModelExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MsgInnerRecExample extends ModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public MsgInnerRecExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public Criteria getCriteria() {
		if (oredCriteria.size() == 0) {
			createCriteria();
		}
		return oredCriteria.get(0);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	public void addCriteria(List<Criterion> criteria) {
		getCriteria().getCriteria().addAll(criteria);
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table msg_inner_rec
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;
		private boolean ignoreNull;

		private boolean isIgnoreNull() {
			return ignoreNull;
		}

		public Criteria ignoreNull() {
			this.ignoreNull = true;
			return (Criteria) this;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException("Value for condition cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition));
			}
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException("Value for " + property + " cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition, value));
			}
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException("Between values for " + property + " cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition, value1, value2));
			}
		}

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterionForJDBCTime(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Time(value.getTime()), property);
		}

		protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				timeList.add(new java.sql.Time(iter.next().getTime()));
			}
			addCriterion(condition, timeList, property);
		}

		protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
		}

		public Criteria andInnerRecIdIsNull() {
			addCriterion("inner_rec_id is null");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdIsNotNull() {
			addCriterion("inner_rec_id is not null");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdEqualTo(Long value) {
			addCriterion("inner_rec_id =", value, "innerRecId");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdNotEqualTo(Long value) {
			addCriterion("inner_rec_id <>", value, "innerRecId");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdGreaterThan(Long value) {
			addCriterion("inner_rec_id >", value, "innerRecId");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdGreaterThanOrEqualTo(Long value) {
			addCriterion("inner_rec_id >=", value, "innerRecId");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdLessThan(Long value) {
			addCriterion("inner_rec_id <", value, "innerRecId");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdLessThanOrEqualTo(Long value) {
			addCriterion("inner_rec_id <=", value, "innerRecId");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdIn(List<Long> values) {
			addCriterion("inner_rec_id in", values, "innerRecId");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdNotIn(List<Long> values) {
			addCriterion("inner_rec_id not in", values, "innerRecId");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdBetween(Long value1, Long value2) {
			addCriterion("inner_rec_id between", value1, value2, "innerRecId");
			return (Criteria) this;
		}

		public Criteria andInnerRecIdNotBetween(Long value1, Long value2) {
			addCriterion("inner_rec_id not between", value1, value2, "innerRecId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdIsNull() {
			addCriterion("template_id is null");
			return (Criteria) this;
		}

		public Criteria andTemplateIdIsNotNull() {
			addCriterion("template_id is not null");
			return (Criteria) this;
		}

		public Criteria andTemplateIdEqualTo(Long value) {
			addCriterion("template_id =", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdNotEqualTo(Long value) {
			addCriterion("template_id <>", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdGreaterThan(Long value) {
			addCriterion("template_id >", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdGreaterThanOrEqualTo(Long value) {
			addCriterion("template_id >=", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdLessThan(Long value) {
			addCriterion("template_id <", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdLessThanOrEqualTo(Long value) {
			addCriterion("template_id <=", value, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdIn(List<Long> values) {
			addCriterion("template_id in", values, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdNotIn(List<Long> values) {
			addCriterion("template_id not in", values, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdBetween(Long value1, Long value2) {
			addCriterion("template_id between", value1, value2, "templateId");
			return (Criteria) this;
		}

		public Criteria andTemplateIdNotBetween(Long value1, Long value2) {
			addCriterion("template_id not between", value1, value2, "templateId");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeIsNull() {
			addCriterion("send_time_type is null");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeIsNotNull() {
			addCriterion("send_time_type is not null");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeEqualTo(String value) {
			addCriterion("send_time_type =", value, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeNotEqualTo(String value) {
			addCriterion("send_time_type <>", value, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeGreaterThan(String value) {
			addCriterion("send_time_type >", value, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeGreaterThanOrEqualTo(String value) {
			addCriterion("send_time_type >=", value, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeLessThan(String value) {
			addCriterion("send_time_type <", value, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeLessThanOrEqualTo(String value) {
			addCriterion("send_time_type <=", value, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeLike(String value) {
			addCriterion("send_time_type like", value, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeNotLike(String value) {
			addCriterion("send_time_type not like", value, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeIn(List<String> values) {
			addCriterion("send_time_type in", values, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeNotIn(List<String> values) {
			addCriterion("send_time_type not in", values, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeBetween(String value1, String value2) {
			addCriterion("send_time_type between", value1, value2, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andSendTimeTypeNotBetween(String value1, String value2) {
			addCriterion("send_time_type not between", value1, value2, "sendTimeType");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andSendStatusIsNull() {
			addCriterion("send_status is null");
			return (Criteria) this;
		}

		public Criteria andSendStatusIsNotNull() {
			addCriterion("send_status is not null");
			return (Criteria) this;
		}

		public Criteria andSendStatusEqualTo(String value) {
			addCriterion("send_status =", value, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusNotEqualTo(String value) {
			addCriterion("send_status <>", value, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusGreaterThan(String value) {
			addCriterion("send_status >", value, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusGreaterThanOrEqualTo(String value) {
			addCriterion("send_status >=", value, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusLessThan(String value) {
			addCriterion("send_status <", value, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusLessThanOrEqualTo(String value) {
			addCriterion("send_status <=", value, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusLike(String value) {
			addCriterion("send_status like", value, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusNotLike(String value) {
			addCriterion("send_status not like", value, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusIn(List<String> values) {
			addCriterion("send_status in", values, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusNotIn(List<String> values) {
			addCriterion("send_status not in", values, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusBetween(String value1, String value2) {
			addCriterion("send_status between", value1, value2, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andSendStatusNotBetween(String value1, String value2) {
			addCriterion("send_status not between", value1, value2, "sendStatus");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeIsNull() {
			addCriterion("redirect_type is null");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeIsNotNull() {
			addCriterion("redirect_type is not null");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeEqualTo(String value) {
			addCriterion("redirect_type =", value, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeNotEqualTo(String value) {
			addCriterion("redirect_type <>", value, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeGreaterThan(String value) {
			addCriterion("redirect_type >", value, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeGreaterThanOrEqualTo(String value) {
			addCriterion("redirect_type >=", value, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeLessThan(String value) {
			addCriterion("redirect_type <", value, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeLessThanOrEqualTo(String value) {
			addCriterion("redirect_type <=", value, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeLike(String value) {
			addCriterion("redirect_type like", value, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeNotLike(String value) {
			addCriterion("redirect_type not like", value, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeIn(List<String> values) {
			addCriterion("redirect_type in", values, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeNotIn(List<String> values) {
			addCriterion("redirect_type not in", values, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeBetween(String value1, String value2) {
			addCriterion("redirect_type between", value1, value2, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectTypeNotBetween(String value1, String value2) {
			addCriterion("redirect_type not between", value1, value2, "redirectType");
			return (Criteria) this;
		}

		public Criteria andRedirectValueIsNull() {
			addCriterion("redirect_value is null");
			return (Criteria) this;
		}

		public Criteria andRedirectValueIsNotNull() {
			addCriterion("redirect_value is not null");
			return (Criteria) this;
		}

		public Criteria andRedirectValueEqualTo(String value) {
			addCriterion("redirect_value =", value, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueNotEqualTo(String value) {
			addCriterion("redirect_value <>", value, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueGreaterThan(String value) {
			addCriterion("redirect_value >", value, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueGreaterThanOrEqualTo(String value) {
			addCriterion("redirect_value >=", value, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueLessThan(String value) {
			addCriterion("redirect_value <", value, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueLessThanOrEqualTo(String value) {
			addCriterion("redirect_value <=", value, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueLike(String value) {
			addCriterion("redirect_value like", value, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueNotLike(String value) {
			addCriterion("redirect_value not like", value, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueIn(List<String> values) {
			addCriterion("redirect_value in", values, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueNotIn(List<String> values) {
			addCriterion("redirect_value not in", values, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueBetween(String value1, String value2) {
			addCriterion("redirect_value between", value1, value2, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andRedirectValueNotBetween(String value1, String value2) {
			addCriterion("redirect_value not between", value1, value2, "redirectValue");
			return (Criteria) this;
		}

		public Criteria andCategoryIsNull() {
			addCriterion("category is null");
			return (Criteria) this;
		}

		public Criteria andCategoryIsNotNull() {
			addCriterion("category is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryEqualTo(Integer value) {
			addCriterion("category =", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotEqualTo(Integer value) {
			addCriterion("category <>", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryGreaterThan(Integer value) {
			addCriterion("category >", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryGreaterThanOrEqualTo(Integer value) {
			addCriterion("category >=", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLessThan(Integer value) {
			addCriterion("category <", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLessThanOrEqualTo(Integer value) {
			addCriterion("category <=", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryIn(List<Integer> values) {
			addCriterion("category in", values, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotIn(List<Integer> values) {
			addCriterion("category not in", values, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryBetween(Integer value1, Integer value2) {
			addCriterion("category between", value1, value2, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotBetween(Integer value1, Integer value2) {
			addCriterion("category not between", value1, value2, "category");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberIsNull() {
			addCriterion("business_number is null");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberIsNotNull() {
			addCriterion("business_number is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberEqualTo(String value) {
			addCriterion("business_number =", value, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberNotEqualTo(String value) {
			addCriterion("business_number <>", value, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberGreaterThan(String value) {
			addCriterion("business_number >", value, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberGreaterThanOrEqualTo(String value) {
			addCriterion("business_number >=", value, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberLessThan(String value) {
			addCriterion("business_number <", value, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberLessThanOrEqualTo(String value) {
			addCriterion("business_number <=", value, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberLike(String value) {
			addCriterion("business_number like", value, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberNotLike(String value) {
			addCriterion("business_number not like", value, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberIn(List<String> values) {
			addCriterion("business_number in", values, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberNotIn(List<String> values) {
			addCriterion("business_number not in", values, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberBetween(String value1, String value2) {
			addCriterion("business_number between", value1, value2, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessNumberNotBetween(String value1, String value2) {
			addCriterion("business_number not between", value1, value2, "businessNumber");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlIsNull() {
			addCriterion("business_url is null");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlIsNotNull() {
			addCriterion("business_url is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlEqualTo(String value) {
			addCriterion("business_url =", value, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlNotEqualTo(String value) {
			addCriterion("business_url <>", value, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlGreaterThan(String value) {
			addCriterion("business_url >", value, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlGreaterThanOrEqualTo(String value) {
			addCriterion("business_url >=", value, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlLessThan(String value) {
			addCriterion("business_url <", value, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlLessThanOrEqualTo(String value) {
			addCriterion("business_url <=", value, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlLike(String value) {
			addCriterion("business_url like", value, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlNotLike(String value) {
			addCriterion("business_url not like", value, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlIn(List<String> values) {
			addCriterion("business_url in", values, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlNotIn(List<String> values) {
			addCriterion("business_url not in", values, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlBetween(String value1, String value2) {
			addCriterion("business_url between", value1, value2, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andBusinessUrlNotBetween(String value1, String value2) {
			addCriterion("business_url not between", value1, value2, "businessUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlIsNull() {
			addCriterion("pic_url is null");
			return (Criteria) this;
		}

		public Criteria andPicUrlIsNotNull() {
			addCriterion("pic_url is not null");
			return (Criteria) this;
		}

		public Criteria andPicUrlEqualTo(String value) {
			addCriterion("pic_url =", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotEqualTo(String value) {
			addCriterion("pic_url <>", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlGreaterThan(String value) {
			addCriterion("pic_url >", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlGreaterThanOrEqualTo(String value) {
			addCriterion("pic_url >=", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlLessThan(String value) {
			addCriterion("pic_url <", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlLessThanOrEqualTo(String value) {
			addCriterion("pic_url <=", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlLike(String value) {
			addCriterion("pic_url like", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotLike(String value) {
			addCriterion("pic_url not like", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlIn(List<String> values) {
			addCriterion("pic_url in", values, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotIn(List<String> values) {
			addCriterion("pic_url not in", values, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlBetween(String value1, String value2) {
			addCriterion("pic_url between", value1, value2, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotBetween(String value1, String value2) {
			addCriterion("pic_url not between", value1, value2, "picUrl");
			return (Criteria) this;
		}

		public Criteria andLiveTimeIsNull() {
			addCriterion("live_time is null");
			return (Criteria) this;
		}

		public Criteria andLiveTimeIsNotNull() {
			addCriterion("live_time is not null");
			return (Criteria) this;
		}

		public Criteria andLiveTimeEqualTo(Date value) {
			addCriterionForJDBCTime("live_time =", value, "liveTime");
			return (Criteria) this;
		}

		public Criteria andLiveTimeNotEqualTo(Date value) {
			addCriterionForJDBCTime("live_time <>", value, "liveTime");
			return (Criteria) this;
		}

		public Criteria andLiveTimeGreaterThan(Date value) {
			addCriterionForJDBCTime("live_time >", value, "liveTime");
			return (Criteria) this;
		}

		public Criteria andLiveTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("live_time >=", value, "liveTime");
			return (Criteria) this;
		}

		public Criteria andLiveTimeLessThan(Date value) {
			addCriterionForJDBCTime("live_time <", value, "liveTime");
			return (Criteria) this;
		}

		public Criteria andLiveTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("live_time <=", value, "liveTime");
			return (Criteria) this;
		}

		public Criteria andLiveTimeIn(List<Date> values) {
			addCriterionForJDBCTime("live_time in", values, "liveTime");
			return (Criteria) this;
		}

		public Criteria andLiveTimeNotIn(List<Date> values) {
			addCriterionForJDBCTime("live_time not in", values, "liveTime");
			return (Criteria) this;
		}

		public Criteria andLiveTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("live_time between", value1, value2, "liveTime");
			return (Criteria) this;
		}

		public Criteria andLiveTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("live_time not between", value1, value2, "liveTime");
			return (Criteria) this;
		}

		public Criteria andDeadTimeIsNull() {
			addCriterion("dead_time is null");
			return (Criteria) this;
		}

		public Criteria andDeadTimeIsNotNull() {
			addCriterion("dead_time is not null");
			return (Criteria) this;
		}

		public Criteria andDeadTimeEqualTo(Date value) {
			addCriterionForJDBCTime("dead_time =", value, "deadTime");
			return (Criteria) this;
		}

		public Criteria andDeadTimeNotEqualTo(Date value) {
			addCriterionForJDBCTime("dead_time <>", value, "deadTime");
			return (Criteria) this;
		}

		public Criteria andDeadTimeGreaterThan(Date value) {
			addCriterionForJDBCTime("dead_time >", value, "deadTime");
			return (Criteria) this;
		}

		public Criteria andDeadTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("dead_time >=", value, "deadTime");
			return (Criteria) this;
		}

		public Criteria andDeadTimeLessThan(Date value) {
			addCriterionForJDBCTime("dead_time <", value, "deadTime");
			return (Criteria) this;
		}

		public Criteria andDeadTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("dead_time <=", value, "deadTime");
			return (Criteria) this;
		}

		public Criteria andDeadTimeIn(List<Date> values) {
			addCriterionForJDBCTime("dead_time in", values, "deadTime");
			return (Criteria) this;
		}

		public Criteria andDeadTimeNotIn(List<Date> values) {
			addCriterionForJDBCTime("dead_time not in", values, "deadTime");
			return (Criteria) this;
		}

		public Criteria andDeadTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("dead_time between", value1, value2, "deadTime");
			return (Criteria) this;
		}

		public Criteria andDeadTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("dead_time not between", value1, value2, "deadTime");
			return (Criteria) this;
		}

		public Criteria andSendTimeIsNull() {
			addCriterion("send_time is null");
			return (Criteria) this;
		}

		public Criteria andSendTimeIsNotNull() {
			addCriterion("send_time is not null");
			return (Criteria) this;
		}

		public Criteria andSendTimeEqualTo(Date value) {
			addCriterion("send_time =", value, "sendTime");
			return (Criteria) this;
		}

		public Criteria andSendTimeNotEqualTo(Date value) {
			addCriterion("send_time <>", value, "sendTime");
			return (Criteria) this;
		}

		public Criteria andSendTimeGreaterThan(Date value) {
			addCriterion("send_time >", value, "sendTime");
			return (Criteria) this;
		}

		public Criteria andSendTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("send_time >=", value, "sendTime");
			return (Criteria) this;
		}

		public Criteria andSendTimeLessThan(Date value) {
			addCriterion("send_time <", value, "sendTime");
			return (Criteria) this;
		}

		public Criteria andSendTimeLessThanOrEqualTo(Date value) {
			addCriterion("send_time <=", value, "sendTime");
			return (Criteria) this;
		}

		public Criteria andSendTimeIn(List<Date> values) {
			addCriterion("send_time in", values, "sendTime");
			return (Criteria) this;
		}

		public Criteria andSendTimeNotIn(List<Date> values) {
			addCriterion("send_time not in", values, "sendTime");
			return (Criteria) this;
		}

		public Criteria andSendTimeBetween(Date value1, Date value2) {
			addCriterion("send_time between", value1, value2, "sendTime");
			return (Criteria) this;
		}

		public Criteria andSendTimeNotBetween(Date value1, Date value2) {
			addCriterion("send_time not between", value1, value2, "sendTime");
			return (Criteria) this;
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_inner_rec
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}