package com.manji.msgservice.model;

import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class MsgSmsRec {

	/**
	 * 发送短息记录ID
	 * @mbggenerated
	 */
	private Long smsRecId;
	/**
	 * 模板id
	 * @mbggenerated
	 */
	private Long templateId;
	/**
	 * 送出去的时间类型：timely:及时。。。temptime:模版定义的时间段。。。customize：自定义时间段
	 * @mbggenerated
	 */
	private String sendTimeType;
	/**
	 * 标题
	 * @mbggenerated
	 */
	private String title;
	/**
	 * 发送内容
	 * @mbggenerated
	 */
	private String content;
	/**
	 * 发送的手机号，多个逗号隔开
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * 执行状态：already:已经执行，wait:还未执行
	 * @mbggenerated
	 */
	private String sendStatus;
	/**
	 * 时间开始
	 * @mbggenerated
	 */
	private Date liveTime;
	/**
	 * 时间结束
	 * @mbggenerated
	 */
	private Date deadTime;
	/**
	 * 发送时间
	 * @mbggenerated
	 */
	private Date sendTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_sms_rec.sms_rec_id
	 * @return  the value of msg_sms_rec.sms_rec_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "发送短息记录ID")
	public Long getSmsRecId() {
		return smsRecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_sms_rec.sms_rec_id
	 * @param smsRecId  the value for msg_sms_rec.sms_rec_id
	 * @mbggenerated
	 */
	public void setSmsRecId(Long smsRecId) {
		this.smsRecId = smsRecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_sms_rec.template_id
	 * @return  the value of msg_sms_rec.template_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "模板id")
	public Long getTemplateId() {
		return templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_sms_rec.template_id
	 * @param templateId  the value for msg_sms_rec.template_id
	 * @mbggenerated
	 */
	public void setTemplateId(Long templateId) {
		this.templateId = templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_sms_rec.send_time_type
	 * @return  the value of msg_sms_rec.send_time_type
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "送出去的时间类型：timely:及时。。。temptime:模版定义的时间段。。。customize：自定义时间段")
	public String getSendTimeType() {
		return sendTimeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_sms_rec.send_time_type
	 * @param sendTimeType  the value for msg_sms_rec.send_time_type
	 * @mbggenerated
	 */
	public void setSendTimeType(String sendTimeType) {
		this.sendTimeType = sendTimeType == null ? null : sendTimeType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_sms_rec.title
	 * @return  the value of msg_sms_rec.title
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "标题")
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_sms_rec.title
	 * @param title  the value for msg_sms_rec.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_sms_rec.content
	 * @return  the value of msg_sms_rec.content
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "发送内容")
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_sms_rec.content
	 * @param content  the value for msg_sms_rec.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_sms_rec.mobile
	 * @return  the value of msg_sms_rec.mobile
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "发送的手机号，多个逗号隔开")
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_sms_rec.mobile
	 * @param mobile  the value for msg_sms_rec.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_sms_rec.send_status
	 * @return  the value of msg_sms_rec.send_status
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "执行状态：already:已经执行，wait:还未执行")
	public String getSendStatus() {
		return sendStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_sms_rec.send_status
	 * @param sendStatus  the value for msg_sms_rec.send_status
	 * @mbggenerated
	 */
	public void setSendStatus(String sendStatus) {
		this.sendStatus = sendStatus == null ? null : sendStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_sms_rec.live_time
	 * @return  the value of msg_sms_rec.live_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "时间开始")
	public Date getLiveTime() {
		return liveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_sms_rec.live_time
	 * @param liveTime  the value for msg_sms_rec.live_time
	 * @mbggenerated
	 */
	public void setLiveTime(Date liveTime) {
		this.liveTime = liveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_sms_rec.dead_time
	 * @return  the value of msg_sms_rec.dead_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "时间结束")
	public Date getDeadTime() {
		return deadTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_sms_rec.dead_time
	 * @param deadTime  the value for msg_sms_rec.dead_time
	 * @mbggenerated
	 */
	public void setDeadTime(Date deadTime) {
		this.deadTime = deadTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_sms_rec.send_time
	 * @return  the value of msg_sms_rec.send_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "发送时间")
	public Date getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_sms_rec.send_time
	 * @param sendTime  the value for msg_sms_rec.send_time
	 * @mbggenerated
	 */
	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}
}