package com.manji.msgservice.model;

import com.manji.msgservice.common.utils.mybatis.model.ModelExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MsgTemplateExample extends ModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public MsgTemplateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public Criteria getCriteria() {
        if (oredCriteria.size() == 0) {createCriteria();}
        return oredCriteria.get(0);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    public void addCriteria(List<Criterion> criteria) {
        getCriteria().getCriteria().addAll(criteria);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_template
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        private boolean ignoreNull;

        private boolean isIgnoreNull() {
            return ignoreNull;
        }

        public Criteria ignoreNull() {
            this.ignoreNull = true;
            return (Criteria) this;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                if (!isIgnoreNull()) {
                    throw new RuntimeException("Value for condition cannot be null");
                }} else {
                    criteria.add(new Criterion(condition));}
                }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                if (!isIgnoreNull()) {
                    throw new RuntimeException("Value for " + property + " cannot be null");
                }} else {
                    criteria.add(new Criterion(condition, value));}
                }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                if (!isIgnoreNull()) {
                    throw new RuntimeException("Between values for " + property + " cannot be null");
                }} else {
                    criteria.add(new Criterion(condition, value1, value2));}
                }

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andTemplateIdIsNull() {
            addCriterion("template_id is null");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIsNotNull() {
            addCriterion("template_id is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateIdEqualTo(Long value) {
            addCriterion("template_id =", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotEqualTo(Long value) {
            addCriterion("template_id <>", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdGreaterThan(Long value) {
            addCriterion("template_id >", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("template_id >=", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLessThan(Long value) {
            addCriterion("template_id <", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLessThanOrEqualTo(Long value) {
            addCriterion("template_id <=", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIn(List<Long> values) {
            addCriterion("template_id in", values, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotIn(List<Long> values) {
            addCriterion("template_id not in", values, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdBetween(Long value1, Long value2) {
            addCriterion("template_id between", value1, value2, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotBetween(Long value1, Long value2) {
            addCriterion("template_id not between", value1, value2, "templateId");
            return (Criteria) this;
        }

        public Criteria andCallNameIsNull() {
            addCriterion("call_name is null");
            return (Criteria) this;
        }

        public Criteria andCallNameIsNotNull() {
            addCriterion("call_name is not null");
            return (Criteria) this;
        }

        public Criteria andCallNameEqualTo(String value) {
            addCriterion("call_name =", value, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameNotEqualTo(String value) {
            addCriterion("call_name <>", value, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameGreaterThan(String value) {
            addCriterion("call_name >", value, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameGreaterThanOrEqualTo(String value) {
            addCriterion("call_name >=", value, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameLessThan(String value) {
            addCriterion("call_name <", value, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameLessThanOrEqualTo(String value) {
            addCriterion("call_name <=", value, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameLike(String value) {
            addCriterion("call_name like", value, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameNotLike(String value) {
            addCriterion("call_name not like", value, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameIn(List<String> values) {
            addCriterion("call_name in", values, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameNotIn(List<String> values) {
            addCriterion("call_name not in", values, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameBetween(String value1, String value2) {
            addCriterion("call_name between", value1, value2, "callName");
            return (Criteria) this;
        }

        public Criteria andCallNameNotBetween(String value1, String value2) {
            addCriterion("call_name not between", value1, value2, "callName");
            return (Criteria) this;
        }

        public Criteria andTempTypeIsNull() {
            addCriterion("temp_type is null");
            return (Criteria) this;
        }

        public Criteria andTempTypeIsNotNull() {
            addCriterion("temp_type is not null");
            return (Criteria) this;
        }

        public Criteria andTempTypeEqualTo(String value) {
            addCriterion("temp_type =", value, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeNotEqualTo(String value) {
            addCriterion("temp_type <>", value, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeGreaterThan(String value) {
            addCriterion("temp_type >", value, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeGreaterThanOrEqualTo(String value) {
            addCriterion("temp_type >=", value, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeLessThan(String value) {
            addCriterion("temp_type <", value, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeLessThanOrEqualTo(String value) {
            addCriterion("temp_type <=", value, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeLike(String value) {
            addCriterion("temp_type like", value, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeNotLike(String value) {
            addCriterion("temp_type not like", value, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeIn(List<String> values) {
            addCriterion("temp_type in", values, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeNotIn(List<String> values) {
            addCriterion("temp_type not in", values, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeBetween(String value1, String value2) {
            addCriterion("temp_type between", value1, value2, "tempType");
            return (Criteria) this;
        }

        public Criteria andTempTypeNotBetween(String value1, String value2) {
            addCriterion("temp_type not between", value1, value2, "tempType");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNull() {
            addCriterion("biz_type is null");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNotNull() {
            addCriterion("biz_type is not null");
            return (Criteria) this;
        }

        public Criteria andBizTypeEqualTo(String value) {
            addCriterion("biz_type =", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotEqualTo(String value) {
            addCriterion("biz_type <>", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThan(String value) {
            addCriterion("biz_type >", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThanOrEqualTo(String value) {
            addCriterion("biz_type >=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThan(String value) {
            addCriterion("biz_type <", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThanOrEqualTo(String value) {
            addCriterion("biz_type <=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLike(String value) {
            addCriterion("biz_type like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotLike(String value) {
            addCriterion("biz_type not like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeIn(List<String> values) {
            addCriterion("biz_type in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotIn(List<String> values) {
            addCriterion("biz_type not in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeBetween(String value1, String value2) {
            addCriterion("biz_type between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotBetween(String value1, String value2) {
            addCriterion("biz_type not between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIsNull() {
            addCriterion("template_name is null");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIsNotNull() {
            addCriterion("template_name is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateNameEqualTo(String value) {
            addCriterion("template_name =", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotEqualTo(String value) {
            addCriterion("template_name <>", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameGreaterThan(String value) {
            addCriterion("template_name >", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameGreaterThanOrEqualTo(String value) {
            addCriterion("template_name >=", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLessThan(String value) {
            addCriterion("template_name <", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLessThanOrEqualTo(String value) {
            addCriterion("template_name <=", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameLike(String value) {
            addCriterion("template_name like", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotLike(String value) {
            addCriterion("template_name not like", value, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameIn(List<String> values) {
            addCriterion("template_name in", values, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotIn(List<String> values) {
            addCriterion("template_name not in", values, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameBetween(String value1, String value2) {
            addCriterion("template_name between", value1, value2, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateNameNotBetween(String value1, String value2) {
            addCriterion("template_name not between", value1, value2, "templateName");
            return (Criteria) this;
        }

        public Criteria andTemplateContentIsNull() {
            addCriterion("template_content is null");
            return (Criteria) this;
        }

        public Criteria andTemplateContentIsNotNull() {
            addCriterion("template_content is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateContentEqualTo(String value) {
            addCriterion("template_content =", value, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentNotEqualTo(String value) {
            addCriterion("template_content <>", value, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentGreaterThan(String value) {
            addCriterion("template_content >", value, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentGreaterThanOrEqualTo(String value) {
            addCriterion("template_content >=", value, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentLessThan(String value) {
            addCriterion("template_content <", value, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentLessThanOrEqualTo(String value) {
            addCriterion("template_content <=", value, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentLike(String value) {
            addCriterion("template_content like", value, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentNotLike(String value) {
            addCriterion("template_content not like", value, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentIn(List<String> values) {
            addCriterion("template_content in", values, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentNotIn(List<String> values) {
            addCriterion("template_content not in", values, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentBetween(String value1, String value2) {
            addCriterion("template_content between", value1, value2, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateContentNotBetween(String value1, String value2) {
            addCriterion("template_content not between", value1, value2, "templateContent");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusIsNull() {
            addCriterion("template_status is null");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusIsNotNull() {
            addCriterion("template_status is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusEqualTo(String value) {
            addCriterion("template_status =", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusNotEqualTo(String value) {
            addCriterion("template_status <>", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusGreaterThan(String value) {
            addCriterion("template_status >", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusGreaterThanOrEqualTo(String value) {
            addCriterion("template_status >=", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusLessThan(String value) {
            addCriterion("template_status <", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusLessThanOrEqualTo(String value) {
            addCriterion("template_status <=", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusLike(String value) {
            addCriterion("template_status like", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusNotLike(String value) {
            addCriterion("template_status not like", value, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusIn(List<String> values) {
            addCriterion("template_status in", values, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusNotIn(List<String> values) {
            addCriterion("template_status not in", values, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusBetween(String value1, String value2) {
            addCriterion("template_status between", value1, value2, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andTemplateStatusNotBetween(String value1, String value2) {
            addCriterion("template_status not between", value1, value2, "templateStatus");
            return (Criteria) this;
        }

        public Criteria andLiveTimeIsNull() {
            addCriterion("live_time is null");
            return (Criteria) this;
        }

        public Criteria andLiveTimeIsNotNull() {
            addCriterion("live_time is not null");
            return (Criteria) this;
        }

        public Criteria andLiveTimeEqualTo(Date value) {
            addCriterionForJDBCTime("live_time =", value, "liveTime");
            return (Criteria) this;
        }

        public Criteria andLiveTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("live_time <>", value, "liveTime");
            return (Criteria) this;
        }

        public Criteria andLiveTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("live_time >", value, "liveTime");
            return (Criteria) this;
        }

        public Criteria andLiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("live_time >=", value, "liveTime");
            return (Criteria) this;
        }

        public Criteria andLiveTimeLessThan(Date value) {
            addCriterionForJDBCTime("live_time <", value, "liveTime");
            return (Criteria) this;
        }

        public Criteria andLiveTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("live_time <=", value, "liveTime");
            return (Criteria) this;
        }

        public Criteria andLiveTimeIn(List<Date> values) {
            addCriterionForJDBCTime("live_time in", values, "liveTime");
            return (Criteria) this;
        }

        public Criteria andLiveTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("live_time not in", values, "liveTime");
            return (Criteria) this;
        }

        public Criteria andLiveTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("live_time between", value1, value2, "liveTime");
            return (Criteria) this;
        }

        public Criteria andLiveTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("live_time not between", value1, value2, "liveTime");
            return (Criteria) this;
        }

        public Criteria andDeadTimeIsNull() {
            addCriterion("dead_time is null");
            return (Criteria) this;
        }

        public Criteria andDeadTimeIsNotNull() {
            addCriterion("dead_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeadTimeEqualTo(Date value) {
            addCriterionForJDBCTime("dead_time =", value, "deadTime");
            return (Criteria) this;
        }

        public Criteria andDeadTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("dead_time <>", value, "deadTime");
            return (Criteria) this;
        }

        public Criteria andDeadTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("dead_time >", value, "deadTime");
            return (Criteria) this;
        }

        public Criteria andDeadTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("dead_time >=", value, "deadTime");
            return (Criteria) this;
        }

        public Criteria andDeadTimeLessThan(Date value) {
            addCriterionForJDBCTime("dead_time <", value, "deadTime");
            return (Criteria) this;
        }

        public Criteria andDeadTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("dead_time <=", value, "deadTime");
            return (Criteria) this;
        }

        public Criteria andDeadTimeIn(List<Date> values) {
            addCriterionForJDBCTime("dead_time in", values, "deadTime");
            return (Criteria) this;
        }

        public Criteria andDeadTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("dead_time not in", values, "deadTime");
            return (Criteria) this;
        }

        public Criteria andDeadTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("dead_time between", value1, value2, "deadTime");
            return (Criteria) this;
        }

        public Criteria andDeadTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("dead_time not between", value1, value2, "deadTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_template
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}